import { vanailaInstructor, vanailaCourses } from './vanaila-seed-data'

const q = (v: string) => `'${v.replace(/'/g, "''")}'`

export function buildVanailaSeedSql(): string {
  const lines: string[] = []
  let lessonCount = 0

  lines.push(
    `INSERT OR IGNORE INTO profiles (id, email, password_hash, name, role, status, avatar_url, bio, created_at) VALUES (${[
      vanailaInstructor.id,
      vanailaInstructor.email,
      'a0',
      vanailaInstructor.name,
      vanailaInstructor.role,
      vanailaInstructor.status,
      vanailaInstructor.avatarUrl,
      vanailaInstructor.bio,
    ].map(q).join(', ')}, CURRENT_TIMESTAMP);`,
  )

  for (const course of vanailaCourses) {
    lines.push('', `-- Course: ${course.title.replace(/\s+/g, ' ')} (${course.category})`)
    lines.push(
      `INSERT OR IGNORE INTO courses (id, instructor_id, title, slug, description, cover_url, category, tags, price, currency, status, created_at) VALUES (${q(course.id)}, ${q(vanailaInstructor.id)}, ${q(course.title)}, ${q(course.slug)}, ${q(course.description)}, ${q(course.coverUrl)}, ${q(course.category)}, ${q(JSON.stringify(course.tags))}, 0, 'USD', 'published', CURRENT_TIMESTAMP);`,
    )
    const secs = course.sections ?? (course.section ? [course.section] : [])
    for (const sec of secs) {
      lines.push(
        `INSERT OR IGNORE INTO sections (id, course_id, title, position) VALUES (${q(sec.id)}, ${q(course.id)}, ${q(sec.title)}, ${sec.position});`,
      )
      for (const l of sec.lessons) {
        lessonCount++
        lines.push(
          `INSERT OR IGNORE INTO lessons (id, section_id, title, type, video_url, position, is_free_preview) VALUES (${q(l.id)}, ${q(sec.id)}, ${q(l.title)}, ${q(l.type)}, ${q(l.videoUrl)}, ${l.position}, ${l.isFreePreview ? 1 : 0});`,
        )
      }
    }
  }

  const header = [
    '-- Vanaila Course LMS Database Seed (generated by scripts/generate-vanaila-sql.ts; do not edit by hand)',
    `-- ${vanailaCourses.length} courses, ${lessonCount} lessons`,
    '',
  ]
  return [...header, ...lines, ''].join('\n')
}
